from django.urls import path
from . import views

urlpatterns = [
    path('<int:home_id>/',views.detail, name = 'detail'),
    path('new/', views.new, name = 'new'),
    path('new_g/', views.new_g, name = 'new_g'),
    path('ad/new/', views.newAd, name='newAd'),
    path('spec/new/', views.newSpec, name='newSpec'),
    path('spec/new_l/', views.newSpec_l, name='newSpec_l'),
    path('create/',views.create, name='create'),
    path('create_g/',views.create_g, name='create_g'),
    path('ad/create/',views.createAd, name='createAd'),
    path('spec/create/',views.createSpec, name='createSpec'),
    path('spec/create_l/',views.createSpec_l, name='createSpec_l'),
    path('<int:home_id>/delete/', views.delete, name = 'delete'),
    path('<int:home_id>/delete_r/', views.delete_r, name = 'delete_r'),
    path('<int:home_id>/delete_a/', views.delete_a, name = 'delete_a'),
    path('<int:home_id>/delete_s/', views.delete_s, name = 'delete_s'),
    path('<int:home_id>/update_c/', views.update_c, name = 'update_c'),
    path('<int:home_id>/update_r/', views.update_r, name = 'update_r'),
    path('<int:home_id>/update_a/', views.update_a, name = 'update_a'),
    path('<int:home_id>/update_s/', views.update_s, name = 'update_s'),
    path('report/',views.report, name='report'),
    path('report_g/',views.report_g, name='report_g'),
    path('ad/',views.ad, name='ad'),
    path('spec/', views.spec, name='spec'),
    path('spec_l/', views.spec_l, name='spec_l'),
    path('<int:home_id>/reportDetail/', views.reportDetail, name='reportDetail'),
    path('<int:home_id>/reportDetail_g/', views.reportDetail_g, name='reportDetail_g'),
    path('<int:home_id>/adDetail/', views.adDetail, name='adDetail'),
    path('<int:home_id>/specDetail/', views.specDetail, name='specDetail'),
    path('<int:home_id>/specDetail_l/', views.specDetail_l, name='specDetail_l'),
    path('revise/', views.revise, name = 'revise'),
]